# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | generator/package-lock.json'
    path: 'generator/node_modules'

- script: |
    cd ./generator
    npm install
  displayName: 'npm install'

- script: |
    cd ./generator
    npm run build-dist
  displayName: 'build'

- script: |
    cd ./generator
    npm run test:with-reporters
  displayName: 'tests'

- script: |
    cd ./generator
    npm run test:compile-check
  displayName: 'compile-check'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: './generator/build/test/report/test-result.xml'

- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

- script: |
    cd ./generator
    npm run test:testcafe-headless
  displayName: 'functional-test'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './generator/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
