name: Publication
on:
  push:
    branches:
      - releases/*
    paths:
      - 'packages/*/package.json'
env:
  nodeVersion: 12.x

jobs:

  version-bump:
    name: Detect version bump
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detection.outputs.changed }}
      version: ${{ steps.detection.outputs.version }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Detect Bump
        id: detection
        uses: ./.github/actions/detect-version-bump

  prepublish-build: 
    name: Prepublish build
    runs-on: ubuntu-latest
    needs: [ version-bump ]
    if: needs.version-bump.outputs.changed

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install --no-audit --no-fund --ignore-scripts

      - name: Bootstrap
        run: npm run bootstrap:ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Pack
        run: npm run pack

      - uses: actions/upload-artifact@master
        with:
          name: devextreme-generator-artifacts
          path: ./packages/*/package.tgz

  publishing:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ prepublish-build ]

    strategy:
      matrix:
        PACKAGE: [
          core-generator,
          angular-generator,
          vue-generator,
          react-generator,
          preact-generator,
          inferno-generator,
          build-helpers,
          declarations,
          vdom,
        ]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.nodeVersion }}
          registry-url: https://registry.npmjs.org/

      - uses: actions/download-artifact@master
        with:
          name: devextreme-generator-artifacts

      - name: Publish ${{ matrix.PACKAGE }}
        run: npm publish ./${{ matrix.PACKAGE }}/package.tgz
        env:
          PACKAGE: ${{ matrix.PACKAGE }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
