# This workflow will run tests for DevExtreme generators

name: DevExtreme generators

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install --no-audit --no-fund --ignore-scripts

      - name: Bootstrap
        run: npm run bootstrap:ci

      - name: Build
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test:with-reporters

      - name: e2e tests
        run: npm run test:testcafe-headless
