# This workflow will run tests for DevExtreme generators

name: DevExtreme generators

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - '**'
env:
  nodeVersion: 16

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.nodeVersion }}

      - name: Install packages
        run: npm install --no-audit --no-fund --ignore-scripts

      - name: Bootstrap
        run: npm run bootstrap:ci

      - name: Print TypeScript version
        run: npm ls --location=global
      
      - name: Print all packages version
        run: npm list

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test

      - name: Tests compilation check
        run: npm run test:compile-check

      - name: e2e tests
        run: npm run test:testcafe-headless

      - name: Runtime tests
        run: npm run test:runtime
        
      - name: Copy test-result artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: ${{ github.workspace }}/packages/tests/report/test-result.xml
          if-no-files-found: ignore
        

      - name: Copy screenshots artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ${{ github.workspace }}/packages/tests/e2e/tests/temp/**/*
          if-no-files-found: ignore
