name: Version
on:
  pull_request:
    paths:
      - 'packages/*/package.json'
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:

  version-bump:
    runs-on: ubuntu-latest
    name: Bump
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Detect version bump
        id: versionBump
        uses: ./.github/actions/detect-version-bump

      - name: Check version bump PR
        if:  steps.versionBump.outputs.changed
        env:
          title: ${{github.event.pull_request.title}}
          version: ${{steps.versionBump.outputs.version}}
        run: |
            errCount=0
            if [[ $title != $version ]]
            then
              echo "::error::PR title should match new version: $version"
              ((errCount+=1))
            fi
            if ! [[ $(git diff HEAD^ HEAD --shortstat) =~ (10 *file *changed.*10 *insertion.*10 *deletion) ]]
            then
              echo "::error::PR with version bump should have no other changes"
              ((errCount+=1))
            fi
            exit $errCount